volumes:
  addons:
  cfg:
  scripts:

networks:
  l4d2-network:

services:
  l4d2:
    image: zonemod/l4d2:latest
    container_name: l4d2
    ports:
      - "27015:27015"
      - "27015:27015/udp"
    environment:
      PORT: 27015
      TZ: Asia/Shanghai
    volumes:
      - addons:/addons
      - cfg:/cfg
      - scripts:/scripts
    networks:
      - l4d2-network
